# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DlqUtils < Formula
  desc "Set of scripts that help with dlq message processing"
  homepage "https://github.com/leoaugustov/dlq-utils"
  url "https://github.com/leoaugustov/dlq-utils/archive/v0.3.0.tar.gz"
  sha256 "33b82770296fd72f530979497fc837df88676b0dbf635d616bfaced93ab1413c"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/leoaugustov/dlq-utils/releases/download/v0.3.0/dlq-utils-0.3.0-darwin-amd64.tar.gz"
      sha256 "e5830b07829234cda43b05a75d66b61b8494ceeaadd3cfe512c7babc27c91cd7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leoaugustov/dlq-utils/releases/download/v0.3.0/dlq-utils-0.3.0-linux-amd64.tar.gz"
      sha256 "71865aef09d1ea06ad761bcac2d28f76097c2515bb4821e881af0d95807726e3"
    end
  end

  def install
    bin.install "dlq-utils"
  end
end
