# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class DlqUtils < Formula
  desc "Set of scripts that help with dlq message processing"
  homepage "https://github.com/leoaugustov/dlq-utils"
  url "https://github.com/leoaugustov/dlq-utils/archive/refs/tags/v0.7.1.tar.gz"
  version "0.7.1"
  sha256 "9eb44456e9b1d0b03d2510a3bd227bd4de759f0cfb57de35a0b1ce3793eba4d5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/leoaugustov/dlq-utils/releases/download/v0.7.1/dlq-utils-0.7.1-darwin-amd64.tar.gz"
      sha256 "8aa615cdfbae53435239805791ada5db044068d5e889ca86fb130ab2effb4265"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leoaugustov/dlq-utils/releases/download/v0.7.1/dlq-utils-0.7.1-linux-amd64.tar.gz"
      sha256 "20a5683736e5a657754dc133e7e52465b06f5500016aba9c460a066bb745c97c"
    end
  end

  def install
    bin.install "dlq-utils"
  end
end
